### ISSUE TITLE
dicom size

### ISSUE THREAD

**Issue by oscarramirezs** [gml16/rl-medical#16]
hi, thanks for this code, it's amazing,
I'm having trouble training the model with my own data, i have some ct scanner with different size between them, for example, 512*512*250, 512*256*128...
So it seems that it is not possible to use this type of data? or what I should do?

thanks for your help

Oscar

**Comment by gml16** [comment]
Hi @oscarramirezs, I’m glad you’re finding this code useful. 
I see 3 possible options to solve this problem:
- You crop all your CT scans to be the same size as your smallest one. 
- You add a margin to all your CT scans to be the same size as your biggest one. 
- You’re welcome to submit a PR to handle variable scan sizes in the code (I don’t think there is any practical reason for it to not be possible). If you need any help with this, I’d be happy to take a look.

**Comment by oscarramirezs** [comment]
@gml16 Thank you for responding. 
Here's what I think from the perspective of creating a code with clinical use. 

- Cropping the size of all  CT scanners to the smallest size doesn't seem like a good solution because it could cut off the region of interest in a scan where one of the landmarks may be located.


- Padding the all scanners to the largest size would be easy to do by  512*512 pixel images,( which is the most common size).
   The problem lies,  it would be difficult to predict largest size Z-axis ( number of images ).
   What can be done is reslicing the CT scans to always have the same number of images. This means that for smaller scanners, 
    new images would be added. For larger scanners, images would be decreased.
    The problem I see with this approach is that when we remove images, we lose information, and when we add images, we 
    introduce unnecessary data, which can slow down calculations and require more CPU or GPU resources.

If you'd like, we can work together to find a good solution. I have a good database that I can modify in diferents ways and share with you.

**Comment by gml16** [comment]
Hi @oscarramirezs, apologies for the slow response. 
I ran the training with some random 3D images that had different dimensions and did not encounter an issue. 
Did you try to train with your current data that has images of different dimensions? If so, could you please elaborate on the error that you are facing (e.g. copy-paste the traceback)?
Feel free to send me your data so that I can try with it directly, you can find my email in my github profile.

**Comment by Vathsan** [comment]
Hey @gml16, I tried training with images (ultrasound) of different sizes and did not encounter any issues. Are there any drawbacks of using different size images? Since, the model takes an input of fixed size `number agents × 4 ×
45 × 45 × 45`, I suppose there will not be any major issues in using images of different sizes.

**Comment by gml16** [comment]
Hi @Vathsan, there should not be any issue with training on images of variable sizes. You just need to make sure that the agents’ starting RoI is within the image (so that it’s not only background).
