### ISSUE TITLE
How to apply this code on 2D images

### ISSUE THREAD

**Issue by JackHeroFly** [gml16/rl-medical#19]
Hello author, thank you for providing the open source code. This work is very interesting. May I ask how to apply this code to 2D images? For example, how to set code parameters when locating some landmarks on a 2D image?

**Comment by gml16** [comment]
Hi @JackHeroFly, thanks for your comment. Unfortunately, this codebase is hardcoded with a 3D volume in mind by design. If you only have a 2D image, the best method may be supervised learning directly from the whole 2D image as input to x-y coordinate. This doesn't work as well for 3D volume due to the curse of dimensionality taking up too much GPU VRAM.

**Comment by JackHeroFly** [comment]
Thank you very much for your reply.
